### ISSUE TITLE
not support for prepend

### ISSUE THREAD

**Issue by wnunez09** [ttskch/select2-bootstrap4-theme#1]
can add support for not support for prepend and Append:

select2-bootstrap4-prepend

**Comment by 808loud** [comment]
I'm assuming this is referencing [input groups](https://getbootstrap.com/docs/4.1/components/input-group/).

**Comment by miguelsmuller** [comment]
It would be great

**Comment by ttskch** [comment]
ok, I'll try 💪

**Comment by TheLoneUs** [comment]
I would also like to vote for this fix. As it stands I'll need to customize this.

The offending classes in bootstrap 4 are `.input-group-prepend` and `.input-group-append`

The appended/prepended input group items are pushed off the same line by the select2 input.

**Comment by ttskch** [comment]
@wnunez09 @808loud @miguelsmuller @TheLoneUs I fixed this via #14. Please check it out 😉
