### ISSUE TITLE
No styling for validation? 

### ISSUE THREAD

**Issue by prionkor** [ttskch/select2-bootstrap4-theme#10]
I am have added required param and submitting empty value. while other fields shows error as expected the select field does not.

**Comment by ttskch** [comment]
@prionkor So sorry for my late response! 🙇And also I don't know how to reproduce the problem, so could you please show me some sample html code which reproduce the problem? Thanks.

**Comment by keithsk** [comment]
Hi ttskch, i also facing same problem as it could not show the border red for the select2 input when the input was validated as empty. I have reproduce the problem, please below

https://jsfiddle.net/keithsk/qLso9zwt/19/

Reference:
https://getbootstrap.com/docs/4.0/components/forms/#validation

**Comment by ttskch** [comment]
@prionkor @keithsk This problem was fixed on [v1.2.3](https://www.npmjs.com/package/@ttskch/select2-bootstrap4-theme/v/1.2.3). Thanks for your feedbacks!

**Comment by keithsk** [comment]
Thank you very much @ttskch
