### ISSUE TITLE
Dropdown incorrectly sets max-height and overflow on group options

### ISSUE THREAD

**Issue by mgoggin** [ttskch/select2-bootstrap4-theme#13]
When using this theme with Select2 on a `<select />` with optgroups the options for each group receive the `.select2-results__options` class. As a result, each group incorrectly has a `max-height` and `overflow` set on it which will scroll each group within the dropdown.

I reckon that only elements which are a direct descendant of `.select2-results`  should have a `max-height` and `overflow`.

Here's an example of this in action.

![2019-04-04 12 15 45](https://user-images.githubusercontent.com/2052785/55583217-f1296700-56e6-11e9-80e6-a02248fae0c8.gif)

Fixed with #12.

**Comment by ttskch** [comment]
closed via #12
