### ISSUE TITLE
There is no top border in dropdowns thatopen upwards.

### ISSUE THREAD

**Issue by Nudasoft** [ttskch/select2-bootstrap4-theme#15]
I noticed that there is no top border in dropdowns that open upwards.

![se_1](https://user-images.githubusercontent.com/30935025/57022136-e1506480-6c4b-11e9-874e-c87aa95755ce.png)

![se3](https://user-images.githubusercontent.com/30935025/57022152-e7464580-6c4b-11e9-9729-4efb4782e8a3.png)

**Comment by ttskch** [comment]
@Nudasoft Thanks for your feedback! I fixed this problem in #16 and bump version to 1.2.2. Please check it out.
