### ISSUE TITLE
Change default color

### ISSUE THREAD

**Issue by jerearaujo03** [ttskch/select2-bootstrap4-theme#17]
How can I change the default selected background color?

<img width="358" alt="Screen Shot 2019-05-15 at 11 46 53 PM" src="https://user-images.githubusercontent.com/7424471/57822846-beee3900-776b-11e9-949e-ad5c10434576.png">

**Comment by ttskch** [comment]
@jerearaujo03 Sorry for my late response. Following css would help you. Thanks.

```html
<style>
  .select2-results__option--highlighted {
    background-color: #f00 !important;
  }
</style>
```

![image](https://user-images.githubusercontent.com/4360663/61109308-8e9eee80-a4bf-11e9-9466-b93459a2907b.png)
