### ISSUE TITLE
Update CDN

### ISSUE THREAD

**Issue by mcandre** [ttskch/select2-bootstrap4-theme#26]
Hi, can we get recent releases published to a CDN, for easier installation?

cdnjs appears to be out of date:

https://cdnjs.com/libraries/select2-bootstrap-theme

**Comment by ttskch** [comment]
@mcandre Your link isn't this library :pray: That's [this](https://github.com/select2/select2-bootstrap-theme). And, this library looks not enough popular yet for being added to cdnjs ([refs](https://github.com/cdnjs/cdnjs/issues/12774#issuecomment-393520257)).
