### ISSUE TITLE
Select groups not properly nested

### ISSUE THREAD

**Issue by sonofliberty** [ttskch/select2-bootstrap4-theme#28]
Had to add this to my scss file to fix:

```
.select2-results__options--nested {
  li {
    padding-left: 1em !important;
  }
}
```

**Comment by ttskch** [comment]
@sonofliberty Thanks for your feedback 👍 Could you please show some sample html which reproduces the problem?

**Comment by bkdotcom** [comment]
https://select2.org/options#dropdown-option-groups

**Comment by leo95works** [comment]
any fix for this?

**Comment by ttskch** [comment]
after 73adaa2, like this 👍 

![image](https://user-images.githubusercontent.com/4360663/80197730-035fa580-865a-11ea-84fb-57dfd63b8931.png)
