### ISSUE TITLE
bug: invalid style for input-group appended input

### ISSUE THREAD

**Issue by ttskch** [ttskch/select2-bootstrap4-theme#36]
![image](https://user-images.githubusercontent.com/4360663/66480016-a8f56200-ead8-11e9-8b38-583a47ed88c5.png)

right side is rounded incorrectly...

**Comment by xjlin0** [comment]
Maybe move the Append element to the left by 1 px?

**Comment by ttskch** [comment]
This is already fixed via #29 👍
