### ISSUE TITLE
No control about overflow

### ISSUE THREAD

**Issue by GeekyMo** [ttskch/select2-bootstrap4-theme#4]
I faced this problem in production and I tried it with the online demo provided in the readme and I'm certain this is the theme's problem. (as the problem wasn't there when I disabled the theme).
Unlike the select2 default theme itself, this theme does not control overflow, try increasing number of your options in the example to over 20.
This will even override the page size and cause the whole page to overflow.
![image](https://user-images.githubusercontent.com/21097871/45912021-0d8b4380-be28-11e8-9314-60d5b78baa2d.png)

**Comment by jlucaspains** [comment]
When comparing the original css for select2 and the one for this theme I found the following missing:

`.select2-results__options {
  max-height: 200px;
  overflow-y: auto;
}`

Add it back and the behavior will be the same.
