### ISSUE TITLE
Select2 (Bootstrap4 Theme) padding issue

### ISSUE THREAD

**Issue by deepak458** [ttskch/select2-bootstrap4-theme#41]
There is some issue with Select2 (Bootstrap4 Theme) height, have a look

![image](https://user-images.githubusercontent.com/29248598/67425073-f9021780-f5f4-11e9-8b78-f5a67308d6ba.png)

**Comment by cspeer** [comment]
Hi,

can you tell me how you fixed the problem since you closed the issue?

Thanks

**Comment by deepak458** [comment]
@cspeer I have added my own padding and overwrite main padding
