### ISSUE TITLE
Weird issue with search not showing complete placeholder.

### ISSUE THREAD

**Issue by Ysovuka** [ttskch/select2-bootstrap4-theme#48]
Weird issue with li width not being set to 100% in css file in dist location. This happens in Chrome Version 81.0.4044.122 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/7169300/80760436-85d6e200-8afe-11ea-889b-0a8bd3e190b5.png)

`    
.select2-search.select2-search--inline {
        width: 100%;
    }
`

Resolves the issue.

![image](https://user-images.githubusercontent.com/7169300/80760610-c6366000-8afe-11ea-9b90-cbcf0b4b9eff.png)

**Comment by ttskch** [comment]
@Ysovuka This problem is fixed via https://github.com/ttskch/select2-bootstrap4-theme/commit/a4cca3a7c66bff362d9ddd91927f108c404d46f1 👍
