### ISSUE TITLE
15 commits of 2020-04-24 waiting for release 1.3.3 on master?

### ISSUE THREAD

**Issue by hartwork** [ttskch/select2-bootstrap4-theme#57]
Hi!

I noticed that there are unreleased fixes sitting on `master`. Are there any plans for the next release?

Thanks and best, Sebastian

**Comment by ttskch** [comment]
It's working in progress on https://github.com/ttskch/select2-bootstrap4-theme/pull/47 🙇

**Comment by hartwork** [comment]
@ttskch #47 looks like it's stuck for close to ya year now. Have you decided for or against use of JavaScript? Do you need someone to discuss options/alternatives to move forward?

I suggest to re-open #57 here in the meantime: I'd personally consider it fixed only after the next release and I won't be the last to wonder about this, either. I'm happy about a rename to a more suitable title, if you like. Thanks!
