### ISSUE TITLE
Use custom-select-% variable instead of input

### ISSUE THREAD

**Issue by claytoncollie** [ttskch/select2-bootstrap4-theme#61]
is there a reason why this package uses the input field variable instead of the `custom-select-%` variables?

https://github.com/twbs/bootstrap/blob/7a6da5e3e7ad7c749dde806546a35d4d4259d965/scss/_variables.scss#L575

I had a custom drop-down indicator on my normal select fields but when I installed this package, I lost that customization. Looking through your source code, it doesnt look like any of these variables are used. 

Is there a particular reason for this?

**Comment by tagliala** [comment]
Hi @claytoncollie, I've noticed the same and I've refactored this theme to use `custom-select` in #67

This is only compatible with the upcoming Select2 4.1 release

**Comment by claytoncollie** [comment]
Looks good. Thank you for the patch.
