### ISSUE TITLE
Styling of dropdown icon does not match BS4 default

### ISSUE THREAD

**Issue by mdr1384** [ttskch/select2-bootstrap4-theme#65]
The icon is a down triangle instead of a down chevron... I tweaked your demo page using the browser console to show the problem:  https://jsfiddle.net/t2prb6ds/

**Comment by ttskch** [comment]
@mdr1384 The icon doesn't depend on Bootstrap itself but it depends on your browser.

Chrome
![](https://tva1.sinaimg.cn/large/008eGmZEgy1gmyu63ovbfj31bs030mwx.jpg)

Safari
![image](https://user-images.githubusercontent.com/4360663/105624363-7950a180-5e64-11eb-8bcd-efdf6db03693.png)

Firefox
![](https://tva1.sinaimg.cn/large/008eGmZEgy1gmyu5rlcbaj315k02ymwx.jpg)

The down triangle icon is default appearance of select2. This theme just extends this appearance.

Thanks.

**Comment by mdr1384** [comment]
Well I'm no expert, like you, but it seems to me if you are offering a style package for bootstrap 4, it should at least do what bootstrap 4 does - I mean they figured out some CSS, you should be able to also - Isn't that the whole point of the BS4 theme? _Right now your dropdown does not look like Bootstrap 4 in ANY of the major browsers_, e.g.:

### **Firefox 84:**
![select2-ff-84](https://user-images.githubusercontent.com/32360633/105702683-244f7280-5eda-11eb-99c9-e698b83b1883.png)

### **Chrome 88:**
![select2-chrome-88](https://user-images.githubusercontent.com/32360633/105702705-2c0f1700-5eda-11eb-8422-68818589ca68.png)

### **Edge 44:**
![select2-edge-44](https://user-images.githubusercontent.com/32360633/105702726-34ffe880-5eda-11eb-8556-cff5ffce3866.png)
